version: '3.1'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.odoo
    depends_on:
      - db
    ports:
      - "8069:8069"
      - "5432:5432"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./odoo-config:/etc/odoo
      - ./dev-addons:/mnt/extra-addons
      - ./log:/var/log/odoo
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=12345678
  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata

volumes:
  odoo-web-data:
  odoo-db-data:
